version: "3.8"
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "8000:8000"

  localstack:
    image: localstack/localstack:3.8.0
    container_name: galactic-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
